-- ============================================================================
-- Madrasatu Darul Arkam
-- Migration 0002: Authorization & Permission Foundation
-- ============================================================================
--
-- Purpose:
--   Establish the database-level permission catalog and role-permission
--   mapping required for production authorization.
--
-- Authorization model:
--   Role -> Permission -> Resource Ownership / Scope -> RLS
--
-- Important:
--   - profiles.role remains authoritative.
--   - Permission definitions are migration-controlled.
--   - Application users cannot modify permission assignments directly.
--   - Resource ownership/scope will be enforced by future domain tables.
--   - No multi-tenant authorization is introduced.
-- ============================================================================

-- ============================================================================
-- PERMISSION CATALOG
-- ============================================================================

create table if not exists public.permissions (
  id bigint generated by default as identity primary key,

  permission_key text not null,
  domain text not null,
  description text not null,

  created_at timestamptz not null default timezone('utc', now()),

  constraint permissions_key_unique
    unique (permission_key),

  constraint permissions_key_format
    check (
      permission_key ~ '^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$'
    ),

  constraint permissions_domain_format
    check (
      domain ~ '^[a-z][a-z0-9_]*$'
    ),

  constraint permissions_description_length
    check (
      char_length(trim(description)) between 1 and 500
    )
);

create index if not exists permissions_domain_idx
  on public.permissions(domain);

-- ============================================================================
-- ROLE -> PERMISSION MAPPING
-- ============================================================================

create table if not exists public.role_permissions (
  role_code public.user_role not null,
  permission_id bigint not null,

  created_at timestamptz not null default timezone('utc', now()),

  primary key (role_code, permission_id),

  constraint role_permissions_permission_fk
    foreign key (permission_id)
    references public.permissions(id)
    on delete restrict
);

create index if not exists role_permissions_permission_idx
  on public.role_permissions(permission_id);

-- ============================================================================
-- PERMISSION CATALOG
-- ============================================================================
--
-- The catalog is controlled by migrations rather than end-user input.
-- ON CONFLICT keeps this migration safe to re-run during development.
-- ============================================================================

insert into public.permissions (
  permission_key,
  domain,
  description
)
values
  ('students.view', 'students', 'View authorized student records'),
  ('students.manage', 'students', 'Create and manage authorized student records'),

  ('academics.view', 'academics', 'View authorized academic records'),
  ('academics.manage', 'academics', 'Manage authorized academic records'),

  ('results.view', 'results', 'View authorized results'),
  ('results.manage', 'results', 'Create and manage authorized results'),
  ('results.publish', 'results', 'Publish approved results'),

  ('attendance.view', 'attendance', 'View authorized attendance records'),
  ('attendance.manage', 'attendance', 'Record and manage authorized attendance'),

  ('finance.view', 'finance', 'View authorized financial records'),
  ('finance.manage', 'finance', 'Manage authorized financial records'),

  ('tahfiz.view', 'tahfiz', 'View authorized Tahfiz records'),
  ('tahfiz.manage', 'tahfiz', 'Manage authorized Tahfiz records'),

  ('communication.view', 'communication', 'View authorized communication records'),
  ('communication.manage', 'communication', 'Manage authorized communication records'),

  ('reports.view', 'reports', 'View authorized reports'),
  ('reports.generate', 'reports', 'Generate authorized reports'),

  ('settings.view', 'settings', 'View authorized system settings'),
  ('settings.manage', 'settings', 'Manage authorized system settings')
on conflict (permission_key) do update
set
  domain = excluded.domain,
  description = excluded.description;

-- ============================================================================
-- ROLE -> PERMISSION BASELINE
-- ============================================================================
--
-- SUPER ADMIN receives the complete current permission catalog.
--
-- Other roles receive only the permissions appropriate to their baseline
-- responsibilities. Resource ownership/scope remains a separate control.
-- ============================================================================

insert into public.role_permissions (role_code, permission_id)
select
  'super_admin'::public.user_role,
  p.id
from public.permissions p
on conflict (role_code, permission_id) do nothing;

insert into public.role_permissions (role_code, permission_id)
select
  r.role_code,
  p.id
from (
  values
    ('school_administrator'::public.user_role, 'students.view'),
    ('school_administrator'::public.user_role, 'students.manage'),
    ('school_administrator'::public.user_role, 'academics.view'),
    ('school_administrator'::public.user_role, 'academics.manage'),
    ('school_administrator'::public.user_role, 'results.view'),
    ('school_administrator'::public.user_role, 'results.manage'),
    ('school_administrator'::public.user_role, 'results.publish'),
    ('school_administrator'::public.user_role, 'attendance.view'),
    ('school_administrator'::public.user_role, 'attendance.manage'),
    ('school_administrator'::public.user_role, 'tahfiz.view'),
    ('school_administrator'::public.user_role, 'tahfiz.manage'),
    ('school_administrator'::public.user_role, 'communication.view'),
    ('school_administrator'::public.user_role, 'communication.manage'),
    ('school_administrator'::public.user_role, 'reports.view'),
    ('school_administrator'::public.user_role, 'reports.generate'),
    ('school_administrator'::public.user_role, 'settings.view')
) as r(role_code, permission_key)
join public.permissions p
  on p.permission_key = r.permission_key
on conflict (role_code, permission_id) do nothing;

insert into public.role_permissions (role_code, permission_id)
select
  r.role_code,
  p.id
from (
  values
    ('principal'::public.user_role, 'students.view'),
    ('principal'::public.user_role, 'academics.view'),
    ('principal'::public.user_role, 'results.view'),
    ('principal'::public.user_role, 'results.manage'),
    ('principal'::public.user_role, 'results.publish'),
    ('principal'::public.user_role, 'attendance.view'),
    ('principal'::public.user_role, 'tahfiz.view'),
    ('principal'::public.user_role, 'communication.view'),
    ('principal'::public.user_role, 'reports.view'),
    ('principal'::public.user_role, 'reports.generate')
) as r(role_code, permission_key)
join public.permissions p
  on p.permission_key = r.permission_key
on conflict (role_code, permission_id) do nothing;

insert into public.role_permissions (role_code, permission_id)
select
  r.role_code,
  p.id
from (
  values
    ('teacher'::public.user_role, 'students.view'),
    ('teacher'::public.user_role, 'academics.view'),
    ('teacher'::public.user_role, 'academics.manage'),
    ('teacher'::public.user_role, 'results.view'),
    ('teacher'::public.user_role, 'results.manage'),
    ('teacher'::public.user_role, 'attendance.view'),
    ('teacher'::public.user_role, 'attendance.manage'),
    ('teacher'::public.user_role, 'tahfiz.view'),
    ('teacher'::public.user_role, 'tahfiz.manage')
) as r(role_code, permission_key)
join public.permissions p
  on p.permission_key = r.permission_key
on conflict (role_code, permission_id) do nothing;

insert into public.role_permissions (role_code, permission_id)
select
  r.role_code,
  p.id
from (
  values
    ('accountant'::public.user_role, 'students.view'),
    ('accountant'::public.user_role, 'finance.view'),
    ('accountant'::public.user_role, 'finance.manage'),
    ('accountant'::public.user_role, 'reports.view'),
    ('accountant'::public.user_role, 'reports.generate')
) as r(role_code, permission_key)
join public.permissions p
  on p.permission_key = r.permission_key
on conflict (role_code, permission_id) do nothing;

insert into public.role_permissions (role_code, permission_id)
select
  r.role_code,
  p.id
from (
  values
    ('student'::public.user_role, 'students.view'),
    ('student'::public.user_role, 'academics.view'),
    ('student'::public.user_role, 'results.view'),
    ('student'::public.user_role, 'attendance.view'),
    ('student'::public.user_role, 'tahfiz.view'),
    ('student'::public.user_role, 'communication.view')
) as r(role_code, permission_key)
join public.permissions p
  on p.permission_key = r.permission_key
on conflict (role_code, permission_id) do nothing;

insert into public.role_permissions (role_code, permission_id)
select
  r.role_code,
  p.id
from (
  values
    ('parent_guardian'::public.user_role, 'students.view'),
    ('parent_guardian'::public.user_role, 'academics.view'),
    ('parent_guardian'::public.user_role, 'results.view'),
    ('parent_guardian'::public.user_role, 'attendance.view'),
    ('parent_guardian'::public.user_role, 'tahfiz.view'),
    ('parent_guardian'::public.user_role, 'communication.view'),
    ('parent_guardian'::public.user_role, 'finance.view')
) as r(role_code, permission_key)
join public.permissions p
  on p.permission_key = r.permission_key
on conflict (role_code, permission_id) do nothing;

-- result_checker intentionally receives no internal database permission.
-- Public result verification will use a dedicated controlled endpoint later.

-- ============================================================================
-- RLS
-- ============================================================================

alter table public.permissions enable row level security;
alter table public.role_permissions enable row level security;

-- Authenticated users may read the permission catalog.
-- This does not grant access to protected school data.
drop policy if exists "permissions_select_authenticated"
on public.permissions;

create policy "permissions_select_authenticated"
on public.permissions
for select
to authenticated
using (true);

-- Role-permission assignments are not directly writable by application users.
-- The authorization helper below reads them through SECURITY DEFINER.
drop policy if exists "role_permissions_select_authenticated"
on public.role_permissions;

create policy "role_permissions_select_super_admin"
on public.role_permissions
for select
to authenticated
using (
  public.current_user_role() = 'super_admin'::public.user_role
);

-- No INSERT / UPDATE / DELETE policies are intentionally created.
-- Permission assignments are controlled through reviewed migrations/admin
-- workflows, not arbitrary client-side writes.

-- ============================================================================
-- AUTHORIZATION HELPER
-- ============================================================================

create or replace function public.has_permission(
  requested_permission text
)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles profile
    join public.role_permissions rp
      on rp.role_code = profile.role
    join public.permissions permission
      on permission.id = rp.permission_id
    where profile.id = auth.uid()
      and profile.status = 'active'
      and permission.permission_key = requested_permission
  );
$$;

-- Only authenticated application users may call the authorization helper.
revoke all on function public.has_permission(text) from public;

grant execute on function public.has_permission(text)
to authenticated;

comment on table public.permissions is
  'Migration-controlled permission catalog for application authorization.';

comment on table public.role_permissions is
  'Migration-controlled mapping between application roles and permissions.';

comment on function public.has_permission(text) is
  'Returns whether the authenticated active user has the requested permission.';

-- ============================================================================
-- END OF MIGRATION 0002
-- ============================================================================
